#!/bin/sh

# Start all init scripts in /etc/init.d
# executing them in numerical order.

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

mount -a

for i in /etc/init.d/S??* ;do
     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

	# No sh extension, so fork subprocess.
	$i start
done
